environment:
  matrix:
#  - JULIAVERSION: "win32"
  - JULIAVERSION: "win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  - cd C:\projects\julia\share\julia\test && C:\projects\julia\bin\julia runtests.jl all
