environment:
  matrix:
  - JULIAVERSION: "win32"
  - JULIAVERSION: "win64"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# temporarily disable backtrace test, failing right now for win64 on master
  - sed -i 's/"backtrace",//' C:/projects/julia/share/julia/test/runtests.jl
#  - cd C:\projects\julia\share\julia && git apply C:\projects\julia-nightly-packaging\file-test.patch
  - cd C:\projects\julia\share\julia\test && C:\projects\julia\bin\julia runtests.jl all
