environment:
  matrix:
  - JULIAVERSION: "x86/0.3/julia-0.3.0-prerelease-win32.exe"
  - JULIAVERSION: "x64/0.3/julia-0.3.0-prerelease-win64.exe"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://s3.amazonaws.com/julialang/bin/winnt/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  - C:\projects\julia\bin\test-julia.bat
